apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: php-deployment 
spec: 
  selector: 
    matchLabels: 
      app: php 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: php 
    spec: 
      containers: 
      - name: php 
        image: icecoderimaj
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: php-service 
spec: 
  selector: 
    app: php 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 32001 
  type: NodePort 
